# Generated by Django 5.2.3 on 2025-07-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
