# Generated by Django 5.2.3 on 2025-07-04 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0007_delete_jobvacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('skills_required', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cybexelapp.department')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cybexelapp.experience')),
            ],
        ),
    ]
