# Generated by Django 5.2.3 on 2025-07-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0012_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
