# Generated by Django 5.2.3 on 2025-07-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0013_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('short_heading', models.CharField(help_text='Heading for card display', max_length=150)),
                ('full_heading', models.CharField(help_text='Complete blog heading for modal view', max_length=250)),
                ('content', models.TextField(help_text='Separate paragraphs with `||`')),
                ('image', models.ImageField(upload_to='blogs/')),
            ],
        ),
    ]
