# Generated by Django 5.2.3 on 2025-07-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0016_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='client_logos/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
