# Generated by Django 5.2.3 on 2025-07-08 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0019_delete_cybexellifeentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CybexelLifeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=200)),
                ('short_sentence', models.TextField()),
                ('para1', models.TextField(blank=True)),
                ('para2', models.TextField(blank=True)),
                ('para3', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cybexel_life/main/')),
            ],
        ),
        migrations.CreateModel(
            name='CybexelLifeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cybexel_life/extra/')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cybexelapp.cybexellifeentry')),
            ],
        ),
    ]
