# Generated by Django 5.2.3 on 2025-07-03 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0004_department_experience_jobvacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobvacancy',
            name='department',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='experience',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='JobVacancy',
        ),
    ]
