# Generated by Django 5.2.3 on 2025-07-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0006_department_experience_jobvacancy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobVacancy',
        ),
    ]
