# Generated by Django 5.2.3 on 2025-07-04 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0008_jobvacancy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobvacancy',
            old_name='skills_required',
            new_name='required_skills',
        ),
    ]
