# Generated by Django 5.2.3 on 2025-07-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0009_rename_skills_required_jobvacancy_required_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
    ]
