# Generated by Django 5.2.3 on 2025-07-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0017_clientlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CybexelLifeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=200)),
                ('short_sentence', models.TextField()),
                ('para1', models.TextField(blank=True)),
                ('para2', models.TextField(blank=True)),
                ('image_paths', models.TextField(help_text='Comma-separated list of image URLs or file paths')),
            ],
        ),
    ]
