# Generated by Django 5.2.3 on 2025-07-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0018_cybexellifeentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CybexelLifeEntry',
        ),
    ]
