# Generated by Django 5.2.3 on 2025-07-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0020_cybexellifeentry_cybexellifeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cybexellifeimage',
            name='entry',
        ),
        migrations.DeleteModel(
            name='CybexelLifeEntry',
        ),
        migrations.DeleteModel(
            name='CybexelLifeImage',
        ),
    ]
