# Generated by Django 5.2.3 on 2025-07-08 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0021_remove_cybexellifeimage_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('para1', models.TextField(blank=True, null=True)),
                ('para2', models.TextField(blank=True, null=True)),
                ('para3', models.TextField(blank=True, null=True)),
                ('category', models.CharField(default='Anniversary', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LifeEventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='life_events/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cybexelapp.lifeevent')),
            ],
        ),
    ]
