# Generated by Django 5.2.4 on 2025-07-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0023_adminprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
