# Generated by Django 5.2.4 on 2025-07-15 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0024_alter_lifeevent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifeevent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lifeevent',
            name='description',
            field=models.TextField(default='No description'),
        ),
    ]
