# Generated by Django 5.2.5 on 2025-11-28 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0025_lifeevent_date_alter_lifeevent_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.ImageField(upload_to='portfolio/category/icons/')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('main_image', models.ImageField(upload_to='portfolio/detail/')),
                ('intro_text', models.TextField()),
                ('process_text', models.TextField()),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cybexelapp.portfoliocategory')),
            ],
        ),
        migrations.CreateModel(
            name='DetailBulletPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullet_points', to='cybexelapp.portfoliodetail')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='cybexelapp.portfoliodetail')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='RecentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(upload_to='portfolio/works/')),
                ('video', models.FileField(blank=True, null=True, upload_to='portfolio/works/videos/')),
                ('title', models.CharField(max_length=150)),
                ('short_text', models.CharField(blank=True, max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_works', to='cybexelapp.portfoliocategory')),
            ],
        ),
    ]
