# Generated by Django 5.2.5 on 2025-12-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0026_portfoliocategory_portfoliodetail_detailbulletpoint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentwork',
            name='category',
        ),
        migrations.RemoveField(
            model_name='portfoliodetail',
            name='category',
        ),
        migrations.RemoveField(
            model_name='processstep',
            name='detail',
        ),
        migrations.DeleteModel(
            name='DetailBulletPoint',
        ),
        migrations.DeleteModel(
            name='RecentWork',
        ),
        migrations.DeleteModel(
            name='PortfolioCategory',
        ),
        migrations.DeleteModel(
            name='PortfolioDetail',
        ),
        migrations.DeleteModel(
            name='ProcessStep',
        ),
    ]
