# Generated by Django 5.2.5 on 2025-12-02 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0027_remove_recentwork_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.ImageField(upload_to='portfolio/category/icons/')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('main_image', models.ImageField(upload_to='portfolio/detail')),
                ('intro_paragraph', models.TextField()),
                ('process_heading', models.CharField(max_length=200)),
                ('process_description', models.TextField()),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cybexelapp.portfoliocategory')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='cybexelapp.portfoliodetail')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='cybexelapp.portfoliodetail')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='portfolio/works/thumbnails/')),
                ('video', models.FileField(blank=True, null=True, upload_to='portfolio/works/videos/')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='cybexelapp.portfoliodetail')),
            ],
        ),
    ]
