# Generated by Django 5.2.5 on 2025-12-03 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0028_portfoliocategory_portfoliodetail_portfoliopoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliopoint',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PortfolioWorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/works/images/')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cybexelapp.portfolioworkitem')),
            ],
        ),
    ]
