# Generated by Django 5.2.5 on 2025-12-03 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0029_alter_portfoliopoint_description_portfolioworkimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioworkitem',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='portfolioworkitem',
            name='video',
        ),
        migrations.AddField(
            model_name='portfolioworkitem',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/works/media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi', 'webm'])]),
        ),
    ]
