# Generated by Django 5.2.5 on 2025-12-03 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0030_remove_portfolioworkitem_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioWorkPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='cybexelapp.portfolioworkitem')),
            ],
        ),
    ]
