# Generated by Django 5.2.5 on 2025-12-04 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0031_portfolioworkpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioworkitem',
            name='media',
        ),
        migrations.AddField(
            model_name='portfolioworkitem',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/works/main/'),
        ),
        migrations.AddField(
            model_name='portfolioworkitem',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/works/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi', 'webm'])]),
        ),
    ]
