# Generated by Django 5.2.5 on 2025-12-04 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0032_remove_portfolioworkitem_media_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/works/images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolioworkitem',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='portfolioworkpoint',
            name='work',
        ),
        migrations.AlterModelOptions(
            name='portfolioprocessstep',
            options={},
        ),
        migrations.RenameField(
            model_name='portfoliopoint',
            old_name='portfolio',
            new_name='category_detail',
        ),
        migrations.RenameField(
            model_name='portfolioprocessstep',
            old_name='portfolio',
            new_name='category_detail',
        ),
        migrations.RemoveField(
            model_name='portfoliopoint',
            name='description',
        ),
        migrations.RemoveField(
            model_name='portfolioprocessstep',
            name='step_number',
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/category/icons/'),
        ),
        migrations.AlterField(
            model_name='portfoliodetail',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfoliodetail', to='cybexelapp.portfoliocategory'),
        ),
        migrations.AlterField(
            model_name='portfoliodetail',
            name='main_image',
            field=models.ImageField(upload_to='portfolio/detail/main/'),
        ),
        migrations.CreateModel(
            name='PortfolioWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='portfolio/works/thumbnails/')),
                ('video', models.FileField(blank=True, null=True, upload_to='portfolio/works/videos/')),
                ('category_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='cybexelapp.portfoliodetail')),
                ('images', models.ManyToManyField(blank=True, to='cybexelapp.workmedia')),
            ],
        ),
        migrations.DeleteModel(
            name='PortfolioWorkImage',
        ),
        migrations.DeleteModel(
            name='PortfolioWorkItem',
        ),
        migrations.DeleteModel(
            name='PortfolioWorkPoint',
        ),
    ]
