# Generated by Django 5.2.5 on 2025-12-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0033_workmedia_remove_portfolioworkitem_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopoint',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
