# Generated by Django 5.2.5 on 2025-12-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0034_portfoliopoint_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliopoint',
            name='description',
        ),
    ]
