# Generated by Django 5.2.5 on 2025-12-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0035_remove_portfoliopoint_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliocategory',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='portfoliodetail',
            name='heading',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='portfoliopoint',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='portfolioprocessstep',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='portfoliowork',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
