# Generated by Django 5.2.5 on 2026-02-12 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0038_lifeeventmedia_delete_lifeeventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='cybexelapp.portfoliocategory'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
