# Generated by Django 5.2.5 on 2026-02-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0039_portfoliocategory_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliocategory',
            name='parent',
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
