# Generated by Django 5.2.5 on 2026-02-12 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0040_remove_portfoliocategory_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliocategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='portfoliodetail',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='cybexelapp.portfoliocategory'),
        ),
        migrations.CreateModel(
            name='PortfolioSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='portfolio/subcategory/icons/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='cybexelapp.portfoliocategory')),
            ],
        ),
        migrations.AddField(
            model_name='portfoliodetail',
            name='subcategory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='cybexelapp.portfoliosubcategory'),
        ),
    ]
