# Generated by Django 5.2.5 on 2026-02-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0041_alter_portfoliocategory_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliodetail',
            name='intro_paragraph',
            field=models.TextField(default='No intro provided yet.'),
        ),
    ]
