# Generated by Django 5.2.5 on 2026-02-21 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0042_alter_portfoliodetail_intro_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliodetail',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='cybexelapp.portfoliosubcategory'),
        ),
    ]
