# Generated by Django 5.2.5 on 2026-02-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybexelapp', '0044_alter_blog_image_alter_clientlogo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
    ]
